language: python
python:
-  3.6
install:
  - pip install mkdocs
  - pip install mkdocs-material
script:
  - mkdocs build --clean

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: site
  on:
    branch: master